### ISSUE TITLE
Polygons not rendering correctly

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#1]
The polygon is acting strange. No idea why. I would fix it if I knew more about hyperbolic geometry. https://gist.github.com/x13machine/f6964cd6df7dd0ec809b

**Comment by ItsNickBarry** [comment]
Yeah, there's a problem with the Point.distantPoint function, which is used to generate regular polygons.  I added a warning to the readme, explaining the program isn't really functional yet.  Hopefully I can get it fixed soon.

**Comment by ItsNickBarry** [comment]
The issue appears to be resolved.  Include the Angle.js file in your HTML, and try your example with the latest commit.  Let me know if you find anything else.  Thanks.
