### ISSUE TITLE
how would I divide a polygon to triangles?

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#10]
I was going to convert the polar coordinates to something like x = angle.cos() * raduis, y = angle.sin() * radius. Then run this library on on the converted output: https://github.com/gfx-rs/genmesh Would this be accurate?

**Comment by ItsNickBarry** [comment]
Yes, that will convert polar coordinates to Cartesian (x, y) coordinates.

**Comment by x13machine** [comment]
I wondering if using Cartesian coordinates ran on an euclidean polygon to triangle algorithm would convert the polygon into triangles accurately.

**Comment by ItsNickBarry** [comment]
I don't see why not.

**Comment by x13machine** [comment]
I'll test it
