### ISSUE TITLE
are hexagon tessellations possible in hyperbolic geometry?

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#11]

**Comment by ItsNickBarry** [comment]
Yes.  For example, [this](https://en.wikipedia.org/wiki/Order-4_hexagonal_tiling).

I intend to eventually add a function to do this automatically.

**Comment by x13machine** [comment]
do squares also work?

**Comment by ItsNickBarry** [comment]
[Yes](https://en.wikipedia.org/wiki/Order-6_square_tiling).

**Comment by x13machine** [comment]
is it possible to make a hyperbolic hexagon tessellation work with hexagon cordinate systems used in http://www.redblobgames.com/grids/hexagons/ ?

**Comment by ItsNickBarry** [comment]
No, all of those functions would have to be modified, and would depend on which particular hexagonal tiling you want to use.

See the table [here](https://en.wikipedia.org/wiki/Uniform_tilings_in_hyperbolic_plane#Regular_hyperbolic_tilings) for some of the infinitely many options available to you.

**Comment by x13machine** [comment]
I was hoping I would able to use tiled to make levels for my game since it has a hexagonal feature. :(

**Comment by x13machine** [comment]
I know, I just convert hexagonal coordinates -> cartesian cordinates -> polar coordinates. so what the sizes are all fucked up.

**Comment by x13machine** [comment]
the algorithm to convert polar coordinates to Beltrami–Klein coordinates is d=tanh(distance);x=sin(angle)*d;y=sin(angle)*d; right?

**Comment by ItsNickBarry** [comment]
I don't know anything about the Beltrami–Klein model except that it is not compatible with the Poincaré model.

I don't know of any hyperbolic coordinate system apart from what I have called "hyperbolic polar coordinates," which consist of a hyperbolic distance from the origin, and an angle.

To convert polar coordinates to hyperbolic polar coordinates:
```
angle = angle
hyperbolicDistance = 2 * atanh(distance)
```

**Comment by x13machine** [comment]
Some guy told me that was the method for Beltrami–Klein. I just thought you might know. I'll just try it. If it doesn't work, ask somewhere else.

**Comment by x13machine** [comment]
your code is shit
