### ISSUE TITLE
Range Error: Maximum Call Stack Size Exceeded in Point.js

### ISSUE THREAD

**Issue by DozenalFTW** [ItsNickBarry/hyperbolic-canvas#12]
When I was working on a hyperbolic geometry idea the Point.js script threw an error with a huge call stack, consisting of these three over and over:
```
isIdealPoint.js:256
getHyperbolicRadiusPoint.js:63
getEuclideanRadiusPoint.js:42
```
Apparently `isIdealPoint` calls `getHyperbolicRadiusPoint` which calls `getEuclideanRadiusPoint` which calls `isIdealPoint`... perhaps, change `isIdealPoint` to not use the other two functions?

**NOTE**: I'm not sure if this bug even exists or if my version of the library is outdated.

**Comment by x13machine** [comment]
that's caused by undefined values in the Point object, I think. The code case is absolute shit.

**Comment by ItsNickBarry** [comment]
@DozenalFTW The current version of `Point.isIdeal()` only calls `Point.getEuclideanRadius()`, which I believe will properly avoid circular calls like that.

**Comment by ItsNickBarry** [comment]
@DozenalFTW  Did you call the Point constructor directly, passing it an options hash?  It's not clear in the documentation, but this is not recommended.  Use the factory methods instead:
```
Point.givenCoordinates(x, y)
Point.givenEuclideanPolarCoordinates(euclideanRadius, angle)
Point.givenHyperbolicPolarCoordinates(hyperbolicRadius, angle)
Point.givenIdealAngle(angle)
```
The constructor requires that specific combinations of attributes be present in the options hash, but doens't actually check to make sure that it has an appropriate combination.  I was able to reproduce your results with `new Point({ angle: 1 }).getEuclideanRadius()`, or `new Point({ angle: 1, hyprbolicRadius: 1 }).getEuclideanRadius()` (note the spelling mistake).

I apologize for the state of the documentation.  Making things like this more clear is one of the next steps.

**Comment by DozenalFTW** [comment]
I also used `player.center.distantPoint(speed, ang);`, where `player.center` is a `Point`.
I also used the variable `Point.CENTER`.

I don't recall using `new Point`...

Here's every single time I use `Point`:

* `var Point = window.Point || window.HyperbolicCanvas.Point;`
* `this.center = Point.givenCoordinates(x, y);`
* `return Line.givenTwoPoints(A, B).hyperbolicDistance();` (came up in my search for `Point`)
* `var mousePoint = Point.givenCoordinates(mouseCoords.x, mouseCoords.y)`
* `if (player.center.equals(Point.CENTER)) return;`
 * `var d2c = player.center.distaceFromCenter();` (looked suspicious)
* `player.center = Point.givenHyperbolicPolarCoordinates(d2c, player.center.angle())`
* `var pt = Point.givenHyperbolicPolarCoordinates(speed, ang);`
* `var pt = player.center.distantPoint(speed, ang);` (came up in the search)
** This is just too much, after here there's nothing new
* I also use `Point.CENTER` a few times

I wonder if some other function is creating the loop. Let me check.

**Comment by DozenalFTW** [comment]
I was going to write this when I found the entire problem.
```javascript
Point.givenCoordinates = function (x, y) {
    return new Point({ x: x, y: y });
  };
``` is faulty. 

> Here's another long post with a bunch of code.
> ```javascript
Point.prototype.getEuclideanRadius = function () {
    if (typeof this._euclideanRadius === 'undefined') {
      if (typeof this._x === 'undefined' || this._y === 'undefined') {
        if (this.getHyperbolicRadius() === Infinity) {
          this._euclideanRadius = 1;
        } else {
          this._euclideanRadius = (Math.exp(this.getHyperbolicRadius()) - 1) /
                                  (Math.exp(this.getHyperbolicRadius()) + 1);
        }
      } else {
        this._euclideanRadius = Math.sqrt(
          Math.pow(this.getX(), 2) +
          Math.pow(this.getY(), 2)
        );
      }
      if (Math.abs(this._euclideanRadius - 1) < 1e-6) {
        this._euclideanRadius = 1;
      }
    }
    return this._euclideanRadius;
  };
```
> So it seems to only call `this.getHyperbolicRadius()` if it's not initialized correctly. OK...
> 
> ```javascript
Point.prototype.getHyperbolicRadius = function () {
    if (typeof this._hyperbolicRadius === 'undefined') {
      if (this.isIdeal()) {
        this._hyperbolicRadius = Infinity;
      } else {
        this._hyperbolicRadius = 2 * Math.atanh(this.getEuclideanRadius());
      }
    }
    return this._hyperbolicRadius;
  };
```
You're calling `this.isIdeal`:
```javascript
Point.prototype.isIdeal = function () {
    return this._euclideanRadius === 1 ||
           this._hyperbolicRadius === Infinity ||
           this.getEuclideanRadius() === 1;
  };
```

> ----

> There have been some changes... `Point.CENTER` is now `Point.ORIGIN` and `Point.prototype.distantPoint` is now `.hyperbolicDistantPoint`.

**Comment by ItsNickBarry** [comment]
I've been renaming things a lot over the past month.  It's bad practice for an API, but that's why there's no release yet.  `Point.CENTER` was renamed to `Point.ORIGIN` on the 1st of April, but `Point.isIdeal` was not added until the 18th of April.  How is it that both exist in the same version?

When you call `Point.givenCoordinates(mouseCoords.x, mouseCoords.y)`, are the `mouseCoords` corrected for the width of the canvas?  I don't think this could cause the problem you're having, but you should use `Canvas.at` to convert coordinates on the page to a `Point`.

If you can tell me the values on the `Point` that causes the recursion, I'll test in the latest version.  It's probably best to update, regardless.  You'll have to rewrite your code to use the updated functions, but a lot has been fixed since the 1st of April.

**Comment by ItsNickBarry** [comment]
What exactly is wrong with `Point.givenCoordinates`?

**Comment by DozenalFTW** [comment]
1. I changed `Point.CENTER` to `Point.ORIGIN` in my actual code.
2. `mouseCoords` is the Euclidean coordinates of the hyperbolic point your mouse is on. (If your mouse is in the center, `mouseCoords` is `{x: 0, y: 0}`. It's a plain object, not a `Point`.
3. All I know is that they are within the plane... as your mouse and player circle move, the points change.
4. It doesn't initialize the values of `_isIdeal`, `_euclideanRadius`, or `_hyperbolicRadius`. It just inits `_x` and `_y`.

**Comment by ItsNickBarry** [comment]
1. Okay.  Maybe I'll allow both.
2. How did you calculate the correct coordinates of the mouse without using `Canvas.at`?  A few things are happening there: the plane is flipped vertically so that positive-y corresponds to "up"; the center of the canvas, rather than the top left, is made to correspond to (0, 0); and the Euclidean radius of the canvas is made to correspond to 1.  Do your `mouseCoords` reflect all of those changes?
3. So the `_x` and `_y` of any `Point` on the plane should be less than 1.
4. That's intentional.  The other values are meant to be calculated as needed.  Do you see where I might have missed a check for undefined values?

**Comment by DozenalFTW** [comment]
(2) I'm actually using a different system for rendering. I wanted an up-close view that only shows a certain Euclidean-rectangle-slice of the disk at once. But I'm confident my code works — it was working before April...

(4) Well, somehow the `isIdeal`, `getEuclideanRadius`, and `getHyperbolicRadius` are linked into an infinite loop. I could send my entire code, but...
The stack of functions is so long I can't see where it's getting called on my end. Only chance is to use a bunch of `try` commands and catch the line it happened on.

**Comment by DozenalFTW** [comment]
Found out the problem is in here:
```javascript
var dst = random(1, 3.9);
var ø = random(360);
var pt = Point.givenHyperbolicPolarCoordinates(dst, ø);
var radius = random(0.08, 0.3);
critters.push(new Critter(pt.x, pt.y, radius));
```

The `Critter` constructor, stripped of everything I *know* isn't the problem:
```javascript
// The Euclidean point that is the hyperbolic center
this.center = Point.givenCoordinates(x, y);
// but a HYPERBOLIC radius.
this.radius = r;

this.circle = Circle.givenHyperbolicCenterRadius(this.center, this.radius);
```
`x` and `y` come directly from a real legit `Point`.

**Comment by ItsNickBarry** [comment]
`pt.x` and `pt.y` are undefined.  Use `pt.getX()` and `pt.getY()`.

**Comment by ItsNickBarry** [comment]
But why not just pass `pt` to the `Critter` constructor?  It should be identical to the new one that is created, aside from floating point errors.

**Comment by DozenalFTW** [comment]
Fixed it, thanks!!

**Comment by ItsNickBarry** [comment]
Let me know if you create something interesting, and I'll link to it when I redo the site.
