### ISSUE TITLE
[Question] How to deal with polar coordinates?

### ISSUE THREAD

**Issue by nemanjajovanovic97** [ItsNickBarry/hyperbolic-canvas#13]
Hello, and thanks for the nice software! It fits best for my school project, so I would like to learn how to use this software, but I'm having troubles understanding it.

Given Poincaree disk, represented as a circle in the Cartesian coordinate system, centered at the origin `(0, 0)` and having radius `1`, I have some questions:

### Question 1

Given a point in hyperbolic plane defined using hyperbolic polar coordinates `(r, φ)` that projects into the point `(x, y)` (Euclidean non-polar coordinates) on the Poincaree disk, how to express `x` and `y` respectively using `r` and `φ`? What formula would it be?

### Question 2

Given two points in hyperbolic plane `P1` and `P2` defined using hyperbolic polar coordinates `(r1, φ1)` and `(r2, φ2)` respectively. Given polar hyperbolic point `P3 (r3, φ3)` as the linear interpolation between `P1` and `P2` parametrized with some variable `k` (between `0` (gives `P1`) and `1` (gives `P2`)). How to express `r3` and `φ3` using `r1, φ1, r2, φ2, k`?

### Question 3

Given hyperbolic line `L1` defined by polar hyperbolic points `(1, 0)` and `(1, π)`. Given hyperbolic line `L2` that is parallel to the `L1` (in hyperbolic plane) and that, when projected to the Poincaree disk, has vertical symmetry. Given hyperbolic polar point `Q` on `L2` that is closest to the origin and hyperbolic distance from `Q` to the origin is `n`, and `Q` projects above the origin on the Poincaree disk. The set of all hyperbolic polar points on line `L2` is defined as `P(k)` where parameter `k` is a real number in range `(-∞, +∞)`, such that for `k < 0` points project to the left side of the Poincaree disk and for `k > 0` points project to the right side of the Poincaree disk, while `P(0)`  is `Q`. Question: how to express `P(k)` using `n` and `k`?

---

Note: I tried to make questions mathematically formal in order to avoid confusion or spoken language imprecision. I was also reading math papers and wikipedia page about hyperbolic geometry, but still can't find answers to these questions.

Regarding question 1: I read source code and if I understand correctly, `x = tanh(r / 2) * cos(φ)` and `y = tanh(r / 2) * sin(φ)`, is that correct? If yes, where did the formula come from?

Regarding question 2, I tried to define two hyperbolic points and draw a line between them by iterating `k` from `0` to `1` and drawing small straight line segments between two consecutive interpolated points. However, no matter what I try, the arc curves to the opposite direction and is mislaced on the Poincaree disk. Same happens regarding question 3: the line curves downwards instead of upwards.

Precise formulas for all 3 questions would be preferred over spoken language explanation, since I am trying to finish my project and I can later understand how it works. Thank you in advance for your time.

**Comment by ItsNickBarry** [comment]
Hey,

I am not a mathematician, and it's been a few years since I've worked with the underlying mathematics of this library, so the best I can do is answer your questions with code.

I recommend that you reverse engineer the examples below if you want to derive a formula, or ask a question on [Mathematics Stack Exchange](https://math.stackexchange.com/) if you need a more detailed answer.

### Answer 1

You can generate a `Point` object using hyperbolic polar coordinates, then use the instance functions to derive euclidean properties:

```javascript
// define using hyperbolic polar coordinates
let point = Point.givenHyperbolicPolarCoordinates(r, φ);
// convert to euclidean coordinates using instance methods
let x = point.getX();
let y = point.getY();
```

### Answer 2

```javascript
let angle = P1.hyperbolicAngleTo(P2);
let distance = P1.hyperbolicDistanceTo(P2);

let P3 = P1.hyperbolicDistantPoint(k * distance, angle);
```

### Answer 3

To get the points `P(k)` along `L2`:

```javascript
let Pk = Q.hyperbolicDistantPoint(k, 0);
```

It looks like I need to add a function to conveniently generate `L2`, but for now you can do this:

```javascript
// k is any nonzero real number (though should be "small" to comply with javascript limitations; ex: k = 1)
let L2 = Line,givenTwoPoints(Q, Q.hyperbolicDistantPoint(k, 0));
```

**Comment by nemanjajovanovic97** [comment]
Nice, thank you. I'll give it a try.
