### ISSUE TITLE
Building a hypertree using hyperbolic-canvas

### ISSUE THREAD

**Issue by alcy** [ItsNickBarry/hyperbolic-canvas#17]
Hi there, thanks for your work on this library! This is just a question, not an issue - I was wondering if you'd recommend using hyperbolic-canvas as a base library for building a hypertree? I know there are some hypertree specific libraries out there, but they are not actively maintained.

**Comment by ItsNickBarry** [comment]
These, right? https://en.wikipedia.org/wiki/Hyperbolic_tree

Yes, this library should work.  The only issue I can think of is that the internal rounding could possibly lead to rendering issues for very large graphs (with nodes very far from the in-focus node).  You might also find the API to be rather quaint, as I designed it almost a decade ago.

Post here if you have any questions.

**Comment by alcy** [comment]
Yep that’s the one, thanks Nick!
