### ISSUE TITLE
Are the units off?

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#3]
I have to radius set to 7 on q polygon to have reach the end of the disk. The maximum x,y is 1. Shouldn't the radius be 1 to reach the end of the screen? why is it 7?

https://gist.github.com/x13machine/7b73802e92efc9380777

**Comment by ItsNickBarry** [comment]
The radius provided to Polygon.fromNCenterRadius is a hyperbolic distance.  Each vertex of the generated Polygon is that distance away from the provided center point.  In this model of the hyperbolic plane, the edge of the unit circle represents a point at infinity, so any distance < infinity will fit within the circle.

Does that make sense?

I haven't decided yet whether I will include functions to create Euclidean polygons.

**Comment by ItsNickBarry** [comment]
Actually, that's not true.  Polygon.fromVertices can be used to define polygons using Euclidean points.  Polygon.fromNCenterRadius is used to generate *regular* polygons on the hyperbolic plane.

**Comment by x13machine** [comment]
so is (1,1) like (infinity,infinity) in hyperbolic space

**Comment by ItsNickBarry** [comment]
Sort of.  I'm not aware of any hyperbolic coordinate system, but (1,1) is an infinite distance away from (0,0).

**Comment by x13machine** [comment]
does hyperbolic-canvas use some sort of hyperbolic coordinate system?

**Comment by ItsNickBarry** [comment]
No.  The Points are defined with standard coordinates relative to the unit circle.  Given two Points, hyperbolic straight lines can be drawn, and hyperbolic distances can be calculated.  Given one Point, a second Point, a specified hyperbolic distance away in a specified direction, can be found.

When generating Points, it might be more intuitive to use the Point.fromPolarCoordinates and Point.fromHyperbolicPolarCoordinates factory methods.

**Comment by x13machine** [comment]
on a pseudo-hyperbolic-coordinate system what would (0.5,0.5) be? how would you convert from the Euclidean-coordinate system to the pseudo-hyperbolic-coordinate

**Comment by ItsNickBarry** [comment]
I don't know.  As far as the canvas is concerned, (.5, .5) is just (.5, .5).  You can get more information about the nature of the point, in a hyperbolic sense, from the instance functions.

```javascript
var point = Point.fromCoordinates(.5, .5);

// get hyperbolic distance from center
var distance = point.distanceFromCenter();

// get angle of point relative the unit circle
var angle = point.angle();

// regenerate the same point using hyperbolic information (though point.equals(newPoint) might be false due to floating point rounding error
var newPoint = Point.fromHyperbolicPolarCoordinates(distance, angle);
```

**Comment by x13machine** [comment]
I figured that I could use 2 * Math.atanh(a) and Math.tanh(a/2) to convert between them.

**Comment by ItsNickBarry** [comment]
I use 2 * Math.atanh(a) to calculate Point.distanceFromCenter, where *a* is the Euclidean distance from the center.  

 Math.tanh(a/2), where *a* is the hyperbolic distance from the center, would return the Euclidean distance from the center.

This is useful, but I don't believe it can be used to generate any sort of (x, y) coordinates.  In the Cartesian coordinate system, x and y represent distances from the y and x axes, respectively.  On the hyperbolic plane, I don't think distance from an axis and distance from the center can be calculated in the same way.

I could be wrong.  I'll look into it.
