### ISSUE TITLE
rendering bug when I add fancy graphics

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#4]
This only happens when I change these:

	c.ctx.shadowColor = color;
	c.ctx.shadowBlur = 40;
	c.ctx.strokeStyle = color;
	c.ctx.lineWidth = 2;

https://gist.github.com/x13machine/1c8344d87a698255b0f6

Any ideas on how I could fix this? I saw something similar happen like this with bezier curves.

**Comment by ItsNickBarry** [comment]
When it spins, you mean?
![screenshot from 2015-06-14 19 03 23](https://cloud.githubusercontent.com/assets/1500628/8151759/0ff9f7ba-12c8-11e5-8b8a-6fd615c8c977.png)

**Comment by x13machine** [comment]
yeah that tick thing. really annoying

**Comment by ItsNickBarry** [comment]
It could be something to do with line 175 of Canvas.js.  I have no idea why, but I had to do 'this.ctx.lineto(x, y)' where *x* and *y* are already the position of the pen.  Without that line, some polygons are filled wrong.

**Comment by ItsNickBarry** [comment]
That is, an arc has been drawn from point *A* to point *B*, and before another arc can be drawn from point *B* to point *C*, a line must be drawn from point *B* to point *B*.

**Comment by ItsNickBarry** [comment]
No, I removed that line and it doesn't fix this problem.

**Comment by ItsNickBarry** [comment]
It doesn't seem to be related to the styling, either.  I removed all but the `c.ctx.strokeStyle = color`, and can still see it.

**Comment by x13machine** [comment]
I think it's something to do with the 	c.ctx.lineWidth = 2;

**Comment by ItsNickBarry** [comment]
I thought so, too, but I removed it, and it still had the problem.

**Comment by x13machine** [comment]
I changed it to 1 and that solved it but I wanted 2px

**Comment by ItsNickBarry** [comment]
width 1:
![screenshot from 2015-06-14 19 20 02](https://cloud.githubusercontent.com/assets/1500628/8151870/641c0e80-12ca-11e5-9838-3d1e253e2fb4.png)

**Comment by ItsNickBarry** [comment]
What browser are you using, by the way?

**Comment by x13machine** [comment]
chrome. you?

**Comment by x13machine** [comment]
try removing the shadowBlur

**Comment by ItsNickBarry** [comment]
Firefox.  Could explain why width of 1 works for you.

**Comment by x13machine** [comment]
what maybe it's not. I did see some flickering. I couldn't find a frame where a tick came up

**Comment by ItsNickBarry** [comment]
I remove all but the color, and it still happens.

**Comment by x13machine** [comment]
maybe it's the floating point

**Comment by x13machine** [comment]
that possible? i dunno

**Comment by ItsNickBarry** [comment]
I don't think so.  It only happens with stroke.  Fill seems to work fine.

**Comment by ItsNickBarry** [comment]
I suppose that doesn't prove that it's not a floating point error.

**Comment by x13machine** [comment]
maybe it's a bug that nobody fixed for 10 years in some low level libarary

**Comment by x13machine** [comment]
what os are you using? I'm thinking it's a bug in linux somewhere

**Comment by ItsNickBarry** [comment]
Ubuntu.

**Comment by ItsNickBarry** [comment]
It gets a bit more clear with a wider stroke.  See that gap?
![screenshot from 2015-06-14 19 34 27](https://cloud.githubusercontent.com/assets/1500628/8152000/6d75479c-12cc-11e5-85f5-d711702f275d.png)

**Comment by ItsNickBarry** [comment]
I'll be away for a bit, but I'll keep looking into this.

**Comment by x13machine** [comment]
I tried it on windows. still happends

**Comment by x13machine** [comment]
when this is fixed I want an option to turn it on and off.
https://gist.github.com/x13machine/a8af1b73ec3eec927f1d

**Comment by ItsNickBarry** [comment]
Ha, we'll see.

**Comment by x13machine** [comment]
I realized It only happens when It's a triangle.
https://gist.github.com/x13machine/711aa9b69469d4eb12a0

**Comment by ItsNickBarry** [comment]
A separate issue occurs for certain canvas size:
![screenshot from 2015-06-18 18 14 33](https://cloud.githubusercontent.com/assets/1500628/8245634/f8112576-15e5-11e5-8ec8-07c48cdd5479.png)

**Comment by x13machine** [comment]
This function seems to do it less:

    function drawPolygon(c,p){
        var vertices = p.vertices;
        var n = vertices.length;
        var start = c.at(vertices[0])
        for (var i = 0; i < n; i++) {
            c.ctx.beginPath();
            c.drawPath(Line.givenTwoPoints(vertices[i], vertices[(i + 1) % n]));
            c.ctx.stroke();
            c.ctx.closePath();
        }
        return true;
    }

**Comment by x13machine** [comment]
I'm think that the other rendering problems are do algorithm problems.

**Comment by ItsNickBarry** [comment]
I tested this with your awesome.html file, and the problem seems to occur just as frequently.  It also now has the problem that I mentioned in my previous comment on the 18th of June.  Since the lines are no longer a part of the same path, the polygon can't be filled.

**Comment by x13machine** [comment]
![hyper](https://cloud.githubusercontent.com/assets/4778150/8559212/ef8972e8-24cf-11e5-9aea-41d31c24fea5.png)

only the player does it

**Comment by ItsNickBarry** [comment]
This can be fixed by setting the `lineJoin` property on the canvas context to "round".

`canvas.setContextProperties({ lineJoin: 'round' });`

Unfortunately, this fix precludes the possibility of sharp corners.  I was able to reduce the effect of the bug, but not remove it entirely, instead modifying the `miterLimit` property.
