### ISSUE TITLE
math problem with wrap around

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#6]
It's suppose to wrap the player around to the other side. Some place it's not working. I'm assuming the math is wrong.
https://gist.github.com/x13machine/5b0f7aba9a91ad351873

**Comment by ItsNickBarry** [comment]
I'm not sure about the coordinate system you're using.  Again, I'm not sure how a coordinate system would work at all on the hyperbolic plane.  I haven't looked into it enough yet.

I did notice one clear problem, however.  When the player travels "straight" across the plane, it follows a Euclidean straight line.  On the hyperbolic plane, straight lines appear as arcs of circles, each such circle intersects is orthogonal to the unit circle.

I will look into the coordinate system when I have an opportunity, but for now I suggest avoiding the use of vectors.  Instead, give the player object a location Point, a speed, and an angle of facing.  Then simply update the player's location using Point.distantPoint:
`player.location = player.location.distantPoint(player.speed, player.angle)`
The point returned by Point.distantPoint will now contain a third attribute in addition to x and y: direction.  This is the direction the player would be facing after having traveled between point and the distantPoint.  If Point.distantPoint is called without specifying an angle, the point is checked for this direction attribute, and that is used if present.

**Comment by ItsNickBarry** [comment]
So, to wrap, you might use this:
```javascript
var currentDistance = player.location.distanceFromCenter();
if (currentDistance > maxDistance) {
  var newPoint = Point.givenHyperbolicPolarCoordinates(2 * maxDistance - currentDistance, player.location.angle() + Math.PI);
  newPoint.direction = player.location.direction;
  player.location = newPoint;
}
```

**Comment by ItsNickBarry** [comment]
I realize this is a bit awkward, with the direction attribute on the returned Point object, but it's the only efficient way.  I'll work on making it more user-friendly.
