### ISSUE TITLE
distantPoint problem

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#8]
https://github.com/ItsNickBarry/hyperbolic-canvas/blob/gh-pages/lib/Point.js#L51
should be:

var point = Point.givenHyperbolicPolarCoordinates(this.distanceFromCenter() - distance,self.distance > distance?thisAngle:angle);

I think that's right.

**Comment by ItsNickBarry** [comment]
What do you mean by "self.distance"?

**Comment by x13machine** [comment]
I meant var point = Point.givenHyperbolicPolarCoordinates(this.distanceFromCenter() - distance,this.distanceFromCenter() > distance?thisAngle:angle);

//there's a bug when you do something like this with the current code:

p1.distantPoint(200.0,Math.PI).distantPoint(100.0,0.0);
// or something like this
p1.distantPoint(100.0,0.0).distantPoint(200.0,Math.PI);

**Comment by x13machine** [comment]
I was converting your code and changing it and there was a bug like that.

**Comment by x13machine** [comment]
https://github.com/ItsNickBarry/hyperbolic-canvas/blob/gh-pages/lib/Line.js#L82 There's a useless Math.abs()

**Comment by ItsNickBarry** [comment]
Ha, looks like both calls to Math.abs() are useless.  Fixed with dfc35ec.

**Comment by x13machine** [comment]
now fix the first bug. This library is poorly designed

**Comment by x13machine** [comment]
This library should use polar coordinates for the coordinates instead of poincare coordinates because like all the algorithms are converting back and forth all the time. Using Polar Coordinates instead of Poincaire Coordinates would increase performance.

**Comment by ItsNickBarry** [comment]
I'm working on it.  Your suggested solution doesn't work any better.

I'm not sure how using polar coordinates would help with this.  It's a hyperbolic library, so it's going to have hyperbolic calculations.  Can you be more specific, or provide documentation?

**Comment by x13machine** [comment]
https://github.com/ItsNickBarry/hyperbolic-canvas/blob/gh-pages/lib/Point.js#L29 

distantPoint basically does poincare coordinates -> polar coordinates -> math -> polar coordinates -> poincare coordinates.

**Comment by x13machine** [comment]
A bunch of functions are like that

**Comment by x13machine** [comment]
There would be a performance increase because the library wouldn't be converting poincare coordinates and polar coordinates all the time. just only at render time

**Comment by ItsNickBarry** [comment]
When you say "Poincare" coordinates, do you mean "Euclidean"?

**Comment by x13machine** [comment]
I think. I dunno whatever new Point({x:0.5,y:0.5}) uses.

**Comment by ItsNickBarry** [comment]
Yes, those are the Euclidean coordinates.  You do have a point about the performance issues, and I'll work on that when I have a chance.  For now, I will prioritize the issues with distantPoint.

**Comment by ItsNickBarry** [comment]
I'm not entirely sure what your original problem was, but I've fixed a problem that occurred when using polar coordinates with a negative radius.

All of the classes now store their instance variables privately: `this._x` instead of `this.x`.  These variables should be retrieved using the new getter methods: `this.getX()`.

When appropriate, these variables are not calculated until the getter is called.  This includes the x and y coordinates of a Point.
