### ISSUE TITLE
how would I check if hyperbolic 2 lines intersect?

### ISSUE THREAD

**Issue by x13machine** [ItsNickBarry/hyperbolic-canvas#9]
does Line.hyperbolicIntersect work?

**Comment by x13machine** [comment]
also how would I get the angle of 2 hyperbolic points?

**Comment by ItsNickBarry** [comment]
There was a small error in the function.  It should be fixed now.  Thanks for pointing it out.

I'm not sure what you mean by your second question.

**Comment by x13machine** [comment]
Math.atan2(x0-x1,y0-y1) <-- whatever the hyperbolic equivalent of that is

**Comment by ItsNickBarry** [comment]
I'm not sure what `Math.atan2(x0-x1,y0-y1)` means in a Euclidean sense.  However, it is my understanding that, because the Poincaré disk model is a "conformal mapping," angles may be measured using Euclidean logic.  No conversion is necessary for angles.

**Comment by x13machine** [comment]
Math.atan2(x0-x1,y0-y1) gets the angle of:
 
var x1=x0+Math.sin(angle)*distance
var y1=y0+Math.cos(angle)*distance

**Comment by x13machine** [comment]
do you know how I would do this?

**Comment by ItsNickBarry** [comment]
I've added a function for this. 
`Point.angleTo(otherPoint)`
Let me know if you find errors.

**Comment by x13machine** [comment]
https://github.com/ItsNickBarry/hyperbolic-canvas/blob/gh-pages/lib/Circle.js#L26 is this correct?

**Comment by x13machine** [comment]
nevermind.

**Comment by x13machine** [comment]
seems to be correct

**Comment by x13machine** [comment]
is Point.angleTo(otherPoint) suppose to get the angle is hyperbolic space? It doesn't seems to work. I converted the code into rust because javascript is to slow.  My rust version doesn't get the correct angle.

**Comment by ItsNickBarry** [comment]
The hyperbolic line between point A and point B is represented by an arc of circle C.  `A.angleTo(B)` should return the angle of the slope of the line tangent to C at A, in the direction of B.

In this example, A is (.5, -.5) and B is (.5, .5).  The result of `A.angleTo(B)` is 2.0344439357957023.  This is the angle of the shown tangent segment to the arc, the angle towards B from A.
![angleto](https://cloud.githubusercontent.com/assets/1500628/14132232/8eaa823c-f611-11e5-9604-d2b4222fbfda.png)

**Comment by x13machine** [comment]
I fucked up while converting your code to rust.
